<template>

    <div>

      <header>

        <app-nav/>

        <full-height class="cover-image d-flex align-items-center" style="background-image: linear-gradient( rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7) ), url('/images/bitcoin-3083578_1920.jpg');">
           <div class="container hero-text">
             <h1>Future Collision Coin</h1>
             <h2>You don't have to trade <strong>Bitcoin</strong> to become super rich</h2>
             <div>
               <a class="btn btn-success" href="#generator">Generate your FCC's now</a>
               <a class="btn btn-danger" href="#monitor">Check your FCC's now</a>
               <a class="btn btn-primary" href="#docs_1">Who we are?</a>
             </div>
           </div>
        </full-height>

      </header>

      <main>

        <section>
            <div class="container" id="docs_1">
              <full-height class="d-flex align-items-center">
                <div class="row">
                  <div class="col-sm">
                    <h2>Who we are?</h2>
                    <p>
                      We are a young and dynamic startup from Würzburg, Germany.
                      We want to change the world of finance in a sustainable way by using <strong>blockchain and cryptocurrencies</strong>.
                      We will generate <strong>future income</strong> from which even your grandchildren will benefit.
                      Sounds good?
                    </p>
                    <div>
                      <a class="btn btn-primary" href="#docs_2">How does it work?</a>
                      <a class="btn btn-success" href="#generator">Generate your keys now</a>
                    </div>
                  </div>
                </div>
              </full-height>
            </div>
        </section>

        <section class="highlight highlight-gray" id="docs_2">
            <div class="container">
              <full-height class="d-flex align-items-center">
                <div class="row">
                  <div class="col-sm">
                    <h2>How does it work?</h2>
                    <p>
                      Crypto currencies like Bitcoin uses cryptographic keys to ensure nobody can take the money. But the keys are limited.
                      The more wallets are generated, the higher the likelihood that one of the keys already exists. This case is called a <strong>cryptographic collision</strong>.
                      This is where Future Collision Coin (FCC) comes into play:
                      This is a payed service, that will generate <strong>thousands of private Bitcoin keys</strong> for you. From time to time you can verify the collision success.
                      If a existing Bitcoin key was found you can simply take the money.
                    </p>
                    <div>
                      <a class="btn btn-primary" href="#docs_3">Are the keys unique?</a>
                      <a class="btn btn-success" href="#generator">Generate your keys now</a>
                    </div>
                  </div>
                </div>
              </full-height>
            </div>
        </section>

        <section id="docs_3">
            <div class="container">
              <full-height class="d-flex align-items-center">
                <div class="row">
                  <div class="col-sm">
                    <h2>Are the keys unique?</h2>
                    <p>
                      Yes! Absolutely! We have created a <strong>super hight performance</strong> algorithm that ensures that every key will only be generated once and never again!
                      Due to this fact we can provide you high quality private key packages.
                      Every key generated by this service is <strong>absolutly unique</strong> and will never be delivered to other users again.
                    </p>
                    <a class="btn btn-success" href="#generator">Generate your package now</a>
                  </div>
                </div>
              </full-height>
            </div>
        </section>

        <section id="generator" class="highlight highlight-gray">
            <div class="container">
              <full-height class="d-flex align-items-center">
                <div class="row">
                  <div class="col">

                    <h2>Generate and download your FCC key package</h2>
                    <package-generator></package-generator>

                  </div>
                </div>
              </full-height>
            </div>
        </section>

        <section id="monitor">
            <div class="container">
              <full-height class="d-flex align-items-center">
                <div class="row">
                  <div class="col">
                    <h2>Upload your FCC key package and find collisions</h2>
                    <package-monitor></package-monitor>
                    <div>
                      <a class="btn btn-success" href="#generator">Generate a new FCC package</a>
                    </div>
                  </div>
                </div>
              </full-height>
            </div>
        </section>

        <section class="highlight highlight-gray" id="disclaimer">
            <div class="container">
              <full-height class="d-flex align-items-center">
                <div class="row">
                  <div class="col-sm">
                    <h2>Disclaimer</h2>
                    <p class="disclaimer">
                      Colliding crypto addresses are very rare! The investment in possibly existing private future keys (FCC's) carries a high risk.
                      You may loose your entire investment.
                    </p>
                    <p class="disclaimer">
                      Never use the generated keys for real transactions! This service will generate real private Bitcoin keys.
                      But the cryptographic random source for the generator is not very trustworthy.
                      It is made for speed and not for security. Furthermore the generation of keys in the browser is not save as they could get grabbed through
                      malware or other attacks. So never use the generated keys for real transactions!
                    </p>
                    <p class="disclaimer">
                      This service will generate real Bitcoin addresses. But it will not realy check your bitcoin keys for a contained ballance.
                      This is because the collision of bitcoin adresses is very rare.
                      Furthermore the collision is so unlikely that it would be more likely that the check function contains an error.
                      Therefore, we decided to leave it empty. That's safer and will lead to the same result.
                    </p>
                    <div>
                      <a class="btn btn-success" href="#generator">Generate your FCC's now</a>
                      <a class="btn btn-danger" href="#monitor">Check your FCC's now</a>
                    </div>
                  </div>
                </div>
              </full-height>
            </div>
        </section>

      </main>

      <app-footer />

    </div>

</template>

<script>
import AppNav from '~/components/AppNav.vue'
import AppFooter from '~/components/AppFooter.vue'
import FullHeight from '~/components/FullHeight.vue'
import PackageGenerator from '~/components/PackageGenerator.vue'
import PackageMonitor from '~/components/PackageMonitor.vue'

export default {
  components: {
    AppNav, AppFooter, FullHeight, PackageGenerator, PackageMonitor
  }
}
</script>

<style>


</style>
