<template>

    <div>

      <header>

        <app-nav/>

        <full-height class="cover-image" style="background-image: url('/images/bitcoin-3083578_1920.jpg');">

          <div class="background-filter">
             <div class="hero-text">
               <h1>Future Collision Coin</h1>
               <h2>You don't have to trade to become super rich</h2>
             </div>
          </div>

        </full-height>

      </header>

      <main>

        <section>
            <div class="container">
              <full-height class="d-flex align-items-center">
                <div class="row">
                  <div class="col-sm">
                    <h2>Who we are?</h2>
                    <p>
                      We are a young and dynamic startup from Würzburg, Germany.
                      We want to change the world of finance in a sustainable way by using <strong>blockchain and cryptocurrencies</strong>.
                      We will generate your <strong>future income</strong> from which even your grandchildren will benefit.
                    </p>
                    <a class="btn btn-success" href="#generator">Generate your keys now</a>
                  </div>
                </div>
              </full-height>
            </div>
        </section>

        <section class="highlight highlight-gray">
            <div class="container">
              <full-height class="d-flex align-items-center">
                <div class="row">
                  <div class="col-sm">
                    <h2>How does it work?</h2>
                    <p>
                      Crypto currencies uses cryptographic keys to ensure nobody can take the money. But the keys are limited.
                      The more wallets are generated, the higher the likelihood that one of the keys already exists. This case is called a <strong>cryptographic collision</strong>.
                      This is where Future Collision Coin (FCC) comes into play:
                      This is a payed service, that will generate <strong>thousands of keys</strong> for you. From time to time you can verify the collision success.
                      If a existing key was found you can simply take the money.
                    </p>
                    <a class="btn btn-success" href="#generator">Generate your keys now</a>
                  </div>
                </div>
              </full-height>
            </div>
        </section>

        <section>
            <div class="container">
              <full-height class="d-flex align-items-center">
                <div class="row">
                  <div class="col-sm">
                    <h2>Are the keys unique?</h2>
                    <p>
                      Yes! Absolutely! We have created a <strong>super hight performance</strong> algorithm that ensures that every key will only be generated once and never again!
                      Due to this fact we can provide you high quality private key packages.
                      Every key generated by this service is <strong>absolutly unique</strong> and will never be delivered to other users of this service.
                    </p>
                    <a class="btn btn-success" href="#generator">Generate your package now</a>
                  </div>
                </div>
              </full-height>
            </div>
        </section>

        <section id="generator" class="highlight highlight-gray">
            <div class="container">
              <full-height class="d-flex align-items-center">
                <div class="row">
                  <div class="col">

                    <h2>Generate and download your FCC key package</h2>

                    <package-generator></package-generator>

                  </div>
                </div>
              </full-height>
            </div>
        </section>

        <section id="monitor">
            <div class="container">
              <full-height class="d-flex align-items-center">
                <div class="row">
                  <div class="col">
                    <h2>Upload your FCC key package and find collisions</h2>
                    <package-monitor></package-monitor>
                  </div>
                </div>
              </full-height>
            </div>
        </section>

      </main>

      <app-footer />

    </div>

</template>

<script>
import AppNav from '~/components/AppNav.vue'
import AppFooter from '~/components/AppFooter.vue'
import FullHeight from '~/components/FullHeight.vue'
import PackageGenerator from '~/components/PackageGenerator.vue'
import PackageMonitor from '~/components/PackageMonitor.vue'

export default {
  components: {
    AppNav, AppFooter, FullHeight, PackageGenerator, PackageMonitor
  }
}
</script>

<style>


</style>
